on:
  push:
    branches: [ main ]

jobs:
  build:
    name: "Build and Deploy"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: rg.fr-par.scw.cloud/funcscwstratovmn5ff0zld
          username: nologin
          password: ${{ secrets.SCW_SECRET_KEY }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./infrastructure/Dockerfile
          push: true
          tags: rg.fr-par.scw.cloud/funcscwstratovmn5ff0zld/pandachain-miniapp-fe:latest
      - name: Use Scaleway CLI
        uses: scaleway/action-scw@v0.0.1
        with:
          save_config: true
          export_config: true
          version: v2.13.0
          access-key: ${{ secrets.SCW_ACCESS_KEY }}
          secret-key: ${{ secrets.SCW_SECRET_KEY }}
          default-project-id: ${{ secrets.SCW_DEFAULT_PROJECT_ID }}
          default-organization-id: ${{ secrets.SCW_DEFAULT_ORGANIZATION_ID }}
          args: container container deploy 89e0e73f-3c58-4b30-86a7-46f4ed38c470
      - name: Scaleway CLI output
        run: echo ${{ steps.cli.outputs.json }}
